import type { NextConfig } from "next";
import createNextIntlPlugin from 'next-intl/plugin';

const withNextIntl = createNextIntlPlugin();

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
      },
      {
        protocol: 'https',
        hostname: 'www.transparenttextures.com',
      },
    ],
  },
  async rewrites() {
    const staticPages = ['onboarding', 'faq', 'payment-success', 'email-preview'];

    // Support both plain and locale-prefixed URLs generated by next-intl
    const beforeFiles = staticPages.flatMap((page) => ([
      { source: `/${page}`, destination: `/${page}.html` },
      { source: '/:locale(es|en)/' + page, destination: `/${page}.html` },
    ]));

    return {
      beforeFiles,
      afterFiles: [],
      fallback: [],
    };
  },
};

export default withNextIntl(nextConfig);
